version: '3.8'

services:
  db:
    image: postgres:16.4
    container_name: postgres
    restart: always
    ports:
        - "5444:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
