name: Pipeline

on:
  push:
    branches:
    - 'main'
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: determine version
        run: |
          VERSION=$(cat VERSION | tr -d ' \t\n\r')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: contains('refs/heads/main', github.ref) || contains('refs/heads/dev', github.ref)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push dev
        if: contains('refs/heads/dev', github.ref)
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: ${{ contains('refs/heads/main', github.ref) }}
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/backup:dev
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push main
        if: contains('refs/heads/main', github.ref)
        uses: docker/build-push-action@v6
        with:
         context: ./docker
         push: true
         tags: ${{ vars.DOCKER_HUB_USERNAME }}/backup:latest, ${{ vars.DOCKER_HUB_USERNAME }}/backup:${{ env.VERSION }}
         platforms: linux/amd64,linux/arm/v7,linux/arm64
         cache-from: type=gha
         cache-to: type=gha,mode=max

  publish-dockerhub-description:
    if: contains('refs/heads/main', github.ref)
    needs:
      - publish-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Dockerhub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ vars.DOCKER_HUB_USERNAME }}/backup
          readme-filepath: ./README.md
